version: '3'
services:
  mysql:
    image: mysql
    environment:
      MYSQL_HOST: ${DB_HOST}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${DB_PORT}:3306
    volumes:
      - ./mysql:/var/lib/mysql
    depends_on:
      - node
  node:
    build: 
      context: .
      dockerfile: Dockerfile
      ports:
        3000:3000
    


