version: '3'
services:
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD : ${DB_PASSWORD}
      MYSQL_USER : ${DB_USER}
      MYSQL_PASSWORD : ${DB_PASSWORD}
    volumes:
      - mysql_node:/var/lib/mysql
    ports:
      - "${DB_PORT}:${MYSQL_PORT}"
volumes:
  mysql_node: